export const fondsList = [
  {
    title: 'Save the Children',
    url: 'https://www.savethechildren.net/what-we-do/emergencies/ukraine-crisis',
    img: './img/save-the-children.png',
    imgRetinaTwo: './img/save-the-children@2x.png',
    imgRetinaThree: './img/save-the-children@3x.png',
  },
  {
    title: 'Project HOPE',
    url: 'https://www.projecthope.org/country/ukraine/',
    img: './img/project-hope.png',
    imgRetinaTwo: './img/project-hope@2x.png',
    imgRetinaThree: './img/project-hope@3x.png',
  },
  {
    title: 'International Medical Corps',
    url: 'https://internationalmedicalcorps.org/country/ukraine/',
    img: './img/international-medical-corps.png',
    imgRetinaTwo: './img/international-medical-corps@2x.png',
    imgRetinaThree: './img/international-medical-corps@3x.png',
  },
  {
    title: 'Medicins Sans Frontieres',
    url: 'https://www.msf.org/ukraine',
    img: './img/medicins-sans-frontieres.png',
    imgRetinaTwo: './img/medicins-sans-frontieres@2x.png',
    imgRetinaThree: './img/medicins-sans-frontieres@3x.png',
  },
  {
    title: 'RAZOM',
    url: 'https://www.razomforukraine.org/',
    img: './img/razom.png',
    imgRetinaTwo: './img/razom@2x.png',
    imgRetinaThree: './img/razom@3x.png',
  },
  {
    title: 'Action against hunger',
    url: 'https://www.actionagainsthunger.org/location/europe/ukraine/',
    img: './img/action-against-hunger.png',
    imgRetinaTwo: './img/action-against-hunger@2x.png',
    imgRetinaThree: './img/action-against-hunger@3x.png',
  },
  {
    title: 'World vision',
    url: 'https://www.wvi.org/emergencies/ukraine',
    img: './img/world-vision.png',
    imgRetinaTwo: './img/world-vision@2x.png',
    imgRetinaThree: './img/world-vision@3x.png',
  },
  {
    title: 'Serhiy Prytula Charity Foundation',
    url: 'https://prytulafoundation.org/en',
    img: './img/serhiy-prytula-charity.png',
    imgRetinaTwo: './img/serhiy-prytula-charity@2x.png',
    imgRetinaThree: './img/serhiy-prytula-charity@3x.png',
  },
  {
    title: 'UNITED24',
    url: 'https://u24.gov.ua/uk',
    img: './img/united24.png',
    imgRetinaTwo: './img/united24@2x.png',
    imgRetinaThree: './img/united24@3x.png',
  },
];
