import './js/preloader';
import './js/support-ukraine';
import './js/shopping_list/shopping-list';
import './js/toggle-color-theme';
import './js/menu';
import './js/toggle-color-theme';
import './js/refs';
import './js/shopping_list/deleteBookBtn'
import './js/modal-auth/modal-window-authFirebase';
import './js/modal-auth/firebaseAuth';